### PR TITLE
Add cert-manager

### PR DESCRIPTION
**Pull request by alexellis**
Essential for TLS certificates on k3s.

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

### CODE REVIEW

**Comment by andyjeffries** [comment]
Fails on image size, can you make sure it's less than 20KB (resize smaller if needed, I use 256x256 normally). Other than that, happy to merge.

**Comment by alexellis** [comment]
Screenshot 2019-09-11 at 13 10 00

**Comment by alexellis** [comment]
Not sure we want to resize any smaller than that. PNG can't be compressed AFAIK.

What would you suggest?

**Comment by andyjeffries** [comment]
I'll merge this and fix it.

**Comment by andyjeffries** [comment]
https://pngcrush.com got it down to 16KB and I then just added a bit of internal spacing and made it square.

**Pull request merged**
